In [1]:
import math
math.sqrt(25)

5.0

In [2]:
math.pi

3.141592653589793

In [16]:
import math as mt
mt.sqrt(25)

5.0

In [11]:
from numpy import random
import numpy as np
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
dataOne

array([[0.92220974, 0.78381649, 0.53173071, 0.76498578, 0.04791913],
       [0.99824796, 0.69840511, 0.66268271, 0.40392036, 0.69812542],
       [0.92698685, 0.82098481, 0.8975653 , 0.44877653, 0.41046257],
       [0.03404446, 0.21861039, 0.5001313 , 0.27533863, 0.78221742],
       [0.04291643, 0.48427809, 0.12636973, 0.25527852, 0.70927654]])

In [12]:
np.mean(dataOne)

0.5378112384873337

In [13]:
np.std(dataOne)

0.29625379647657213

In [14]:
np.histogram(dataOne)

(array([4, 1, 2, 2, 3, 1, 3, 4, 2, 3], dtype=int64),
 array([0.03404446, 0.13046481, 0.22688516, 0.32330551, 0.41972586,
        0.51614621, 0.61256656, 0.70898691, 0.80540726, 0.90182761,
        0.99824796]))

In [19]:
np.square(10)

100

In [1]:
print('I Love data Science')

I Love data Science


In [2]:
variableName = 25
variableName1 = 'I Love data Science'
print(variableName1)
print(variableName)

I Love data Science
25


In [3]:
type(variableName)

int

In [1]:
variableName = 25.0
type(variableName)

float

In [3]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [2]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [4]:
varOne = "25"
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

25Hello


In [6]:
listName = [ ]
listOne = [1,2,3,4]
print(listOne[1:3])
print(listOne[0:2])

[2, 3]
[1, 2]


In [7]:
tel = {'jack': 4098, 'sape': 4139}
tel['jack']

4098

In [18]:
squares = {1:1, 2:4, 3:9, 4:16, 5:25} 
key=(1,3,5)
d1 = {k: squares[k] for k in key}
print(d1)

{1: 1, 3: 9, 5: 25}


In [21]:
d = {1:2, 3:4, 5:6, 7:8}
l = (1,5)
d2={k:d[k] for k in l}
print(d2)

{1: 2, 5: 6}


In [25]:
import math as mt
mt.sqrt(squares[1])
mt.sqrt(squares[4])
mt.sqrt(squares[5])

5.0

In [26]:
mt.sqrt(squares[4])

4.0

In [27]:
mt.sqrt(squares[1])

1.0

In [28]:
mt.exp(squares[1])

2.718281828459045

In [29]:
mt.exp(squares[3])

8103.083927575384

In [30]:
mt.exp(squares[5])

72004899337.38588

In [31]:
mt.log(squares[1])

0.0

In [32]:
mt.log(squares[2])

1.3862943611198906

In [33]:
mt.log(squares[5])

3.2188758248682006

In [37]:
squares = {x: x*x for x in range(6)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [38]:
squares = {1:1, 2:4, 3:9, 4:16, 5:25} 
key=(1,2,3,4,5)
d3 = {k: mt.log(squares[k]) for k in key}
print(d3)

{1: 0.0, 2: 1.3862943611198906, 3: 2.1972245773362196, 4: 2.772588722239781, 5: 3.2188758248682006}


with open(r'C:\Users\Qing\Downloads\baseball.csv','r') as open_file:
    print('baseball.csv content:\n' +open_file.read())

    #In the beginning I received the following error.
    #SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3:
    #After that, I searched google then I find the solution. I added r before the location of the file,which prevent \ 
    #stand for escape and it worked well.

with open(r'C:\Users\Qing\Downloads\baseball.csv','r') as open_file:
    for observation in open_file:
        print ('Reading Data:'+ observation)

In [28]:
n=2
with open(r'C:\Users\Qing\Downloads\baseball.csv','r') as open_file:
    for j,observation in enumerate(open_file):
        if j % n==0:
            print('Reading Line:' +str(j)+'Content：' + observation)

Reading Line:0Content："Name","Team","Position","Height","Weight","Age","PosCategory"

Reading Line:2Content："Paul_Bako","BAL","Catcher",74,215,34.69,"Catcher"

Reading Line:4Content："Kevin_Millar","BAL","First_Baseman",72,210,35.43,"Infielder"

Reading Line:6Content："Brian_Roberts","BAL","Second_Baseman",69,176,29.39,"Infielder"

Reading Line:8Content："Melvin_Mora","BAL","Third_Baseman",71,200,35.07,"Infielder"

Reading Line:10Content："Adam_Stern","BAL","Outfielder",71,180,27.05,"Outfielder"

Reading Line:12Content："Freddie_Bynum","BAL","Outfielder",73,180,26.96,"Outfielder"

Reading Line:14Content："Brandon_Fahey","BAL","Outfielder",74,160,26.11,"Outfielder"

Reading Line:16Content："Jay_Payton","BAL","Outfielder",70,185,34.27,"Outfielder"

Reading Line:18Content："Hayden_Penn","BAL","Starting_Pitcher",75,185,22.38,"Pitcher"

Reading Line:20Content："Daniel_Cabrera","BAL","Starting_Pitcher",79,230,25.76,"Pitcher"

Reading Line:22Content："Jaret_Wright","BAL","Starting_Pitcher",74,230,31.17

In [30]:
from random import random
sample_size=0.25
with open(r'C:\Users\Qing\Downloads\baseball.csv','r') as open_file:
    for j,observation in enumerate(open_file):
        if random()<=sample_size:
            print('Reading Line:' + str(j)+ 'content:'+ observation)

Reading Line:1content:"Adam_Donachie","BAL","Catcher",74,180,22.99,"Catcher"

Reading Line:2content:"Paul_Bako","BAL","Catcher",74,215,34.69,"Catcher"

Reading Line:6content:"Brian_Roberts","BAL","Second_Baseman",69,176,29.39,"Infielder"

Reading Line:8content:"Melvin_Mora","BAL","Third_Baseman",71,200,35.07,"Infielder"

Reading Line:9content:"Aubrey_Huff","BAL","Third_Baseman",76,231,30.19,"Infielder"

Reading Line:16content:"Jay_Payton","BAL","Outfielder",70,185,34.27,"Outfielder"

Reading Line:17content:"Erik_Bedard","BAL","Starting_Pitcher",73,189,27.99,"Pitcher"

Reading Line:18content:"Hayden_Penn","BAL","Starting_Pitcher",75,185,22.38,"Pitcher"

Reading Line:25content:"John_Parrish","BAL","Relief_Pitcher",71,192,29.26,"Pitcher"

Reading Line:29content:"Brian_Burres","BAL","Relief_Pitcher",73,182,25.89,"Pitcher"

Reading Line:30content:"Kurt_Birkins","BAL","Relief_Pitcher",74,188,26.55,"Pitcher"

Reading Line:36content:"Toby_Hall","CWS","Catcher",75,240,31.36,"Catcher"

Reading L

In [31]:
import datetime
datetime.datetime.now()

datetime.datetime(2018, 8, 23, 17, 27, 47, 245275)

In [32]:
str(datetime.datetime.now().date())

'2018-08-23'

In [37]:
def SayHello():
    print('Hello There!')
SayHello()

Hello There!


In [38]:
def DoSum(Value1, Value2):
    return Value1 + Value2
DoSum(2,3)

5

In [48]:
def DisplaySum(Value1, Value2):
    print(str(Value1) + ' + ' + str(Value2) + ' = ' + 
    str((Value1 + Value2)))
DisplaySum(2,3)

2 + 3 = 5


In [49]:
def SayHello(Greeting = 'No Value Supplied'):
    print(Greeting)
SayHello()


No Value Supplied


In [50]:
def SayHello(Greeting = 'No Value Supplied'):
    print(Greeting)
SayHello("Howdy!")

Howdy!


In [53]:
def DisplayMulti(ArgCount = 0, *VarArgs):
    print('You passed ' + str(ArgCount) + ' arguments.',
        VarArgs)
DisplayMulti(3,'Hello',1, True)

You passed 3 arguments. ('Hello', 1, True)


In [56]:
def TestValue(Value):
    if Value == 5:
        print('Values equals 5!')
    elif Value ==6:
        print('Values equals 6!')
    else:
        print('Value is something else.')
        print('It equals ' + str(Value))
TestValue(10)

Value is something else.
It equals 10


In [57]:
def SecretNumber():
    one=int(input('Type a number between 1 and 10:'))
    Two=int(input('Type a number between 1 and 10:'))
    if (one >= 1) and (one <=10):
        if(Two>= 1) and (Two <=10):
            print('Your secret number is: ' + str(one * Two))
        else:
             print('Incorrect second value!') 
    else:
       print('Incorrect first value!')
SecretNumber()

Type a number between 1 and 10:2
Type a number between 1 and 10:9
Your secret number is: 18


In [7]:
def DisplayMulti(*VarArgs):
    for Arg in VarArgs:
        if Arg.upper()=='CONT':
            continue
            print('Continue Argument: ' + Arg)
        elif Arg.upper()=='BREAK':
            break
        print('Good Argument: ' + Arg)
DisplayMulti('Hello','Goodbye','First','Last')

Good Argument: Hello
Good Argument: Goodbye
Good Argument: First
Good Argument: Last


In [5]:
DisplayMulti('Hello','Cont','Goodbye','Break','Last')

Good Argument: Hello
Good Argument: Goodbye


In [16]:
def SecretNumber():
    GotIt = False
    while GotIt == False:
        one=int(input('Type a number between 1 and 10:'))
        Two=int(input('Type a number between 1 and 10:'))
        
        if (one >= 1) and (one <=10):
            if(Two>= 1) and (Two <=10):
                print('Your secret number is: ' + str(one * Two))
                GotIt = True
                continue
            else:
                print('Incorrect second value!') 
        else:
           print('Incorrect first value!')
        print('Try again!')
SecretNumber()

Type a number between 1 and 10:20
Type a number between 1 and 10:30
Incorrect first value!
Try again!
Type a number between 1 and 10:20
Type a number between 1 and 10:10
Incorrect first value!
Try again!
Type a number between 1 and 10:10
Type a number between 1 and 10:3
Your secret number is: 30


In [37]:
SetA = set(['Red','Blue','Green','Black'])
SetB = set(['Black','Green','Yellow','Orange'])
SetX = SetA.union(SetB)
SetY = SetA.intersection(SetB)
SetZ = SetA.difference(SetB)
c=SetA.issuperset(SetY)
SetA.add('Purple')
d=SetA.issubset(SetX)
print(SetX)
print(SetY)
print(SetZ)
print(c)
print(d)

{'Green', 'Blue', 'Yellow', 'Red', 'Orange', 'Black'}
{'Green', 'Black'}
{'Red', 'Blue'}
True
False


In [36]:
engineers = set(['John', 'Jane', 'Jack', 'Janice'])
programmers = set(['Jack', 'Sam', 'Susan', 'Janice'])
managers = set(['Jane', 'Jack', 'Susan', 'Zack'])
employees = engineers | programmers | managers  
print(employees)

{'Jane', 'Sam', 'Zack', 'John', 'Janice', 'Susan', 'Jack'}


In [44]:
ListA=[0,1,2,3]
ListB=[4,5,6,7]
ListA.extend(ListB)
ListA

[0, 1, 2, 3, 4, 5, 6, 7]

In [45]:
ListA.append(-5)
ListA.remove(2)
ListA

[0, 1, 3, 4, 5, 6, 7, -5]

In [47]:
MyTuple=(1,2,3,(4,5,6,(7,8,9)))
for Value1 in MyTuple:
    if type(Value1) == int:
        print (Value1)
    else:
        for Value2 in Value1:
            if type(Value2)== int:
                print ("\t", Value2)
            else:
                for Value3 in Value2:
                    print ("\t\t", Value3)

1
2
3
	 4
	 5
	 6
		 7
		 8
		 9


In [2]:
ListA=['Orange','Yellow','Green','Brown']
ListB=[1,2,3,4]
for Value in ListB[1:3]:
    print(Value)

2
3


In [4]:
for Value1,Value2 in zip(ListA, ListB):
    print (Value1, '\t', Value2)

Orange 	 1
Yellow 	 2
Green 	 3
Brown 	 4


In [8]:
MyDict={'Orange':1,'Blue':2,'Pink':3}
MyDict.keys()

dict_keys(['Orange', 'Blue', 'Pink'])

In [11]:
MyDict={'Orange':1,'Blue':2,'Pink':3}
MyDict.values()

dict_values([1, 2, 3])